# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\"4\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\x1d\n\x05Todos\x12\x14\n\x05todos\x18\x01 \x03(\x0b\x32\x05.Todo\"\x07\n\x05\x45mpty2+\n\x0bTodoService\x12\x1c\n\x08GetTodos\x12\x06.Empty\x1a\x06.Todos\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TODO']._serialized_start=14
  _globals['_TODO']._serialized_end=66
  _globals['_TODOS']._serialized_start=68
  _globals['_TODOS']._serialized_end=97
  _globals['_EMPTY']._serialized_start=99
  _globals['_EMPTY']._serialized_end=106
  _globals['_TODOSERVICE']._serialized_start=108
  _globals['_TODOSERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
